### ISSUE TITLE
Gathering Ores Is Still Broken Due To A Typo

### ISSUE THREAD

**Issue by amirparsadd** [peter-hunt/skyblock#15]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/data/data/com.termux/files/home/skyblock/skyblock/__main__.py", line 18, in <module>
    skyblock_main()
  File "/data/data/com.termux/files/home/skyblock/skyblock/__main__.py", line 14, in skyblock_main
    main()
  File "/data/data/com.termux/files/home/skyblock/skyblock/function/util.py", line 35, in result
    return func(*args, **kwargs)                             ^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/skyblock/skyblock/menu.py", line 127, in main
    profile.mainloop()                              File "/data/data/com.termux/files/home/skyblock/skyblock/function/util.py", line 35, in result        return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/skyblock/skyblock/profile/function/main.py", line 467, in mainloop
    self.gather(name, tool_index, amount)
  File "/data/data/com.termux/files/home/skyblock/skyblock/function/util.py", line 35, in result        return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^                    File "/data/data/com.termux/files/home/skyblock/skyblock/profile/function/grind.py", line 453, in gather                                                self.stats['ores_mined'] += 1
    ~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'ores_mined'

**Comment by peter-hunt** [comment]
I can't find the source code of the addressed problem. Maybe try pulling the newest version?
