### ISSUE TITLE
Mining issue

### ISSUE THREAD

**Issue by DudeChill** [peter-hunt/skyblock#16]
i was trying to mine coal and got the following error
`:> mine coal_ore 3 10
+ Coal
 COLLECTION UNLOCKED Coal
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\alexg\skyblock\skyblock\__main__.py", line 18, in <module>
    skyblock_main()
  File "C:\Users\alexg\skyblock\skyblock\__main__.py", line 14, in skyblock_main
    main()
  File "C:\Users\alexg\skyblock\skyblock\function\util.py", line 35, in result
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexg\skyblock\skyblock\menu.py", line 64, in main
    lastest_profile.mainloop()
  File "C:\Users\alexg\skyblock\skyblock\function\util.py", line 35, in result
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexg\skyblock\skyblock\profile\function\main.py", line 467, in mainloop
    self.gather(name, tool_index, amount)
  File "C:\Users\alexg\skyblock\skyblock\function\util.py", line 35, in result
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexg\skyblock\skyblock\profile\function\grind.py", line 453, in gather
    self.stats['ores_mined'] += 1
    ~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'ores_mined'`

**Comment by TreesOnTop** [comment]
This problem should be fixed now in the latest commit
