### ISSUE TITLE
unkown issue

### ISSUE THREAD

**Issue by DudeChill** [peter-hunt/skyblock#7]
`PS C:\Users\alexg> git clone https://github.com/peter-hunt/skyblock.git
Cloning into 'skyblock'...
remote: Enumerating objects: 3289, done.
remote: Counting objects: 100% (495/495), done.
remote: Compressing objects: 100% (319/319), done.
Rremote: Total 3289 (delta 301), reused 320 (delta 167), pack-reused 2794eceiving objects:  97% (3191/3289), 2.71 MiB | 758.00
Receiving objects: 100% (3289/3289), 2.72 MiB | 763.00 KiB/s, done.
Resolving deltas: 100% (2473/2473), done.
PS C:\Users\alexg> cd skyblock
PS C:\Users\alexg\skyblock> python -m skyblock
Installing Assets...
Assets Installed!
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\alexg\skyblock\skyblock\__main__.py", line 18, in <module>
    skyblock_main()
  File "C:\Users\alexg\skyblock\skyblock\__main__.py", line 14, in skyblock_main
    main()
  File "C:\Users\alexg\skyblock\skyblock\function\util.py", line 34, in result
    return func(*args, **kwargs)
  File "C:\Users\alexg\skyblock\skyblock\menu.py", line 51, in main
    clear()
  File "C:\Users\alexg\skyblock\skyblock\function\util.py", line 44, in clear
    call(['clear'])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by peter-hunt** [comment]
Are you running on windows? This project is only intended for Mac/Linus systems.
I also seem to miss the subprocess module in the requirements.txt, I'll add that soon.

**Comment by peter-hunt** [comment]
Wait, it's the problem inside the module...
I'm sorry but this project currently doesn't support Windows (cuz I can't get it to work on Windows)
