### ISSUE TITLE
runned python -m skyblock and...

### ISSUE THREAD

**Issue by Oofys-death-world** [peter-hunt/skyblock#8]
I ran the command in command prompt in inside the skyblock-main folder
I have Python 3.11

this is the error I:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\*****\Desktop\****** supplies\Other\Skyblock\skyblock-main\skyblock\__main__.py", line 18, in <module>
    skyblock_main()
  File "C:\Users\****\Desktop\******* supplies\Other\Skyblock\skyblock-main\skyblock\__main__.py", line 12, in skyblock_main
    init()
  File "C:\Users\*****\Desktop\****** supplies\Other\Skyblock\skyblock-main\skyblock\install.py", line 41, in init
    install_data()
  File "C:\Users\*****\Desktop\****** supplies\Other\Skyblock\skyblock-main\skyblock\install.py", line 29, in install_data
    run(['rm', '-rf', data_dir])
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 546, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\******\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1491, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by peter-hunt** [comment]
The code was working fine for me, and I'm using the full path to find the data folder, so I'm not entirely sure what's the problem yet. However, I've added a `try` statement to bypass the error when the `pathlib` doesn't work as intended. Please pull the newer version soon and try again!
